apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: tommcc-cluster
  region: eu-north-1
  tags:
    owner: tom.mccarthy@mongodb.com
    expire-on: "2022-10-01"
    expires-on: "2022-10-01"
    purpose: "training"

vpc:
  clusterEndpoints: 
    publicAccess: true
  subnets:
    public:
      eu-north-1a: { id: subnet-0e858860a48876ca9 }
      eu-north-1b: { id: subnet-05278b36d2c015e88 }

nodeGroups:
  - name: nodegroup-1
    labels: { role: workers }
    instanceType: m5.large
    desiredCapacity: 3
    minSize: 3
    maxSize: 4
    preBootstrapCommands:
      - "echo vm.max_map_count=1677720 >> /etc/sysctl.conf"
      - "sysctl -w vm.max_map_count=1677720"
    tags:
      owner: tom.mccarthy@mongodb.com
      expire-on: "2022-10-30"
      expires-on: "2022-10-30"
      purpose: "training"
