---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: prod-db-om
spec:
  version: "6.0.0-ent"
  opsManager:
    configMapRef:
      name: my-project
  credentials: om-credentials
  type: ReplicaSet
  members: 3
  persistent: true
  security:
    authentication:
      enabled : true
      modes: ["SCRAM"]
  backup:
    mode: enabled
---
apiVersion: mongodb.com/v1
kind: MongoDBUser
metadata:
 name: prod-database-user
spec:
  mongodbResourceRef:
    name: prod-db-om
  username: prod-user
  db: "admin"
  passwordSecretKeyRef:
    name: prod-db-user-password
    key: password
  roles:
    - db: "admin"
      name: "clusterAdmin"
    - db: "admin"
      name: "userAdminAnyDatabase"
    - db: "admin"
      name: "readWriteAnyDatabase"
    - db: "admin"
      name: "userAdminAnyDatabase"
