---
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: om-tommcc
spec:
  replicas: 1
  version: 6.0.3
  adminCredentials: admin-user-credentials
  externalConnectivity:
    type: LoadBalancer
  backup:
    enabled: true
    headDB:
      storage: "4Gi" # optional. Default storage is 30G
    members: 1 # Configures the number of backup daemons to create (default 1)
    opLogStores:
      - name: oplog
        mongodbResourceRef:
          name: opsmanager-oplog
        mongodbUserRef:
          name: dbadmin-opsmanager-oplog
    blockStores:
      - name: blockstore
        mongodbResourceRef:
          name: opsmanager-blockstore
        mongodbUserRef:
          name: dbadmin-opsmanager-blockstore
  configuration:
    mms.ignoreInitialUiSetup: "true"
    mms.adminEmailAddr:   tom.mccarthy@mongodb.com
    mms.fromEmailAddr:    tom.mccarthy@mongodb.com
    mms.replyToEmailAddr: tom.mccarthy@mongodb.com
    mms.mail.hostname: smtp-svc.mongodb.svc.cluster.local
    mms.mail.port: "25"
    mms.mail.ssl: "false"
    mms.mail.transport: smtp
    mms.user.bypassInviteForExistingUsers: "true"
    mms.publicApi.whitelistEnabled: "false"
    automation.versions.source: remote # hybrid
    mongodb.release.autoDownload: "false" # stop downloads of binaries (unless you need to demo recovery)
    mongodb.release.autoDownload.enterprise: "true"
    mongodb.release.modulePreference: enterpriseRequired
    # brs.queryable.pem: /opt/mongodb/mms/secrets/queryable-backup.pem # stored in a secret
    brs.queryable.expiration: "3600000"
  applicationDatabase:
    members: 3
    version: 5.0.9-ent
