apiVersion: v1
kind: Secret
metadata:
  name: prod-db-user-password
type: Opaque
stringData:
  password: prod-password
---
apiVersion: v1
kind: Secret
metadata:
  name: oplog-user-password
type: Opaque
stringData:
  password: oplog-user-password
---
apiVersion: v1
kind: Secret
metadata:
  name: blockstore-user-password
type: Opaque
stringData:
  password: blockstore-user-password