apiVersion: mongodb.com/v1
kind: MongoDBUser
metadata:
 name: my-database-user
spec:
  mongodbResourceRef:
    name: prod-db-cm
  username: prod-user
  db: "admin"
  passwordSecretKeyRef:
    name: cm-prod-db-user-password
    key: password
  roles:
    - db: "admin"
      name: "clusterAdmin"
    - db: "admin"
      name: "userAdminAnyDatabase"
    - db: "admin"
      name: "readWriteAnyDatabase"
    - db: "admin"
      name: "userAdminAnyDatabase"
---
apiVersion: v1
kind: Secret
metadata:
  name: cm-prod-db-user-password
type: Opaque
stringData:
  password: prod-password