apiVersion: atlas.mongodb.com/v1
kind: AtlasBackupPolicy
metadata:
  name: atlas-default-backuppolicy
  namespace: mongodb
spec:
   items:
      - frequencyType: "hourly"
        frequencyInterval: 6
        retentionUnit: "days"
        retentionValue: 7
      - frequencyType: "daily"
        frequencyInterval: 1
        retentionUnit: "days"
        retentionValue: 7
      - frequencyType: "weekly"
        frequencyInterval: 6
        retentionUnit: "weeks"
        retentionValue: 4
      - frequencyType: "monthly"
        frequencyInterval: 1
        retentionUnit: "months"
        retentionValue: 12
---
apiVersion: atlas.mongodb.com/v1
kind: AtlasBackupSchedule
metadata:
  name: atlas-default-backupschedule
  namespace: mongodb
spec:
  referenceHourOfDay: 10
  referenceMinuteOfHour: 10
  restoreWindowDays: 2
  policy:
    name: atlas-default-backuppolicy
    namespace: mongodb