---
apiVersion: v1
kind: Pod
metadata:
  name: mongosh-atlas
  namespace: mongodb
spec:
  containers:
  - name: mongosh
    image: rtsp/mongosh:latest
    env:
      - name: "CONNECTIONSTRING"
        valueFrom:
          secretKeyRef:
            name: tom-mccarthy-demo-project-k8s-cluster-atlasuser
            key: connectionStringStandardSrv
